Repository AICoE/aicoe-cd, pull requests merged in 2020-09, with the labels that each got.

#99 Add idh dev cluster
  docs/admin/add_new_cluster_spec.md
  manifests/overlays/prod/secrets/clusters/api.ocp4.idh.dev.datahub.redhat.com.enc.yaml
  manifests/overlays/prod/secrets/clusters/secret-generator.yaml
Labels: approved, size/M

#102 Add newlines for better readability
  docs/admin/add_new_cluster_spec.md
Labels: approved, size/XS

#101 Update Cluster Server
  manifests/overlays/prod/secrets/clusters/api.ocp4.idh.dev.datahub.redhat.com.enc.yaml
Labels: approved, size/XS

#103 Add '*' inclusions to idh server
  manifests/overlays/prod/configs/argo_cm/resource.inclusions
Labels: approved, size/XS

#105 Minor doc fixes.
  README.md
  docs/setup_argocd_dev_environment.md
  mkdocs.yml
Labels: approved, size/S

#104 Add stage environment for mi
  manifests/overlays/prod/applications/thoth-station/stage/stage-thoth-mi.yaml
Labels: approved, size/S

#106 update aicoe-ci repository url
  manifests/overlays/prod/configs/argo_cm/repositories
Labels: approved, size/XS

#107 allow pipeline to be setup in ocp cluster
  manifests/overlays/prod/configs/argo_cm/resource.inclusions
Labels: approved, size/S

#108 support aicoe-ci deployment with aicoe-cd
  manifests/overlays/prod/applications/thoth-station/bots/aicoe-ci.yaml
  manifests/overlays/prod/applications/thoth-station/kustomization.yaml
Labels: approved, size/S

#110 Add aiops prod argo namespace to ocp4
  manifests/overlays/prod/secrets/clusters/apps.ocp.prod.psi.redhat.com.enc.yaml
Labels: approved, do-not-merge/hold, size/XS

#111 Remove argocd build assets
  .aicoe-ci.yaml
  Dockerfile
  build-pipeline.yaml
Labels: size/L

#112 Update pr template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: size/S

#113 Update argocd to reference 1.7.4 from operate-first
  docs/versions.md
  manifests/base/kustomization.yaml
  manifests/base/resources/deployments/argocd-repo-server_patch.yaml
  manifests/base/resources/deployments/argocd-server_patch.yaml
  manifests/base/resources/routes/argocd_server_route.yaml
  manifests/base/resources/serviceaccounts/argocd-manager.yaml
  manifests/base/resources/services/argocd_metrics_service_patch.yaml
  manifests/base/resources/services/argocd_server_metrics_service_patch.yaml
  manifests/crds/aggregate-to-admin.yaml
  manifests/crds/kustomization.yaml
Labels: approved, do-not-merge/hold, size/L

#114 Add aicoe-infra-prod to namespaces
  manifests/overlays/prod/secrets/clusters/apps.ocp.prod.psi.redhat.com.enc.yaml
Labels: size/XS

#115 Remove non-functioning clusters from ArgoCD
  manifests/overlays/prod/secrets/clusters/api.aasthana.dev.datahub.redhat.com.enc.yaml
  manifests/overlays/prod/secrets/clusters/api.ocp4.idh.dev.datahub.redhat.com.enc.yaml
  manifests/overlays/prod/secrets/clusters/secret-generator.yaml
Labels: approved, size/M

#116 support more thoth-station application with aicoe-cd
  manifests/overlays/prod/applications/thoth-station/kustomization.yaml
  manifests/overlays/prod/applications/thoth-station/stage/stage-thoth-graph-backup.yaml
  manifests/overlays/prod/applications/thoth-station/stage/stage-thoth-investigator.yaml
  manifests/overlays/prod/applications/thoth-station/test/test-thoth-graph-backup.yaml
Labels: approved, size/M

#117 Migrate OpenshiftSME to OCP prod
  manifests/overlays/prod/applications/aiops/argo-analytics.yaml
Labels: approved, size/XS

#109 Add aiops prod argo
  manifests/overlays/prod/configs/argo_cm/resource.inclusions
Labels: approved, size/S

#118 Fix thoth-station graph-backup-job overlay path
  manifests/overlays/prod/applications/thoth-station/stage/stage-thoth-graph-backup.yaml
  manifests/overlays/prod/applications/thoth-station/test/test-thoth-graph-backup.yaml
Labels: approved, size/XS

#119 Update url for internal data hub manifests repo
  manifests/overlays/prod/configs/argo_cm/repositories
Labels: approved, size/XS

#120 Update idh apps to point at correct repository
  manifests/overlays/prod/applications/aiops/aiops-prod-argo.yaml
  manifests/overlays/prod/applications/data_hub/dh-prod-jupyterhub.yaml
  manifests/overlays/prod/applications/data_hub/dh-prod-kafka.yaml
  manifests/overlays/prod/applications/data_hub/dh-psi-monitoring.yaml
  manifests/overlays/prod/applications/data_hub/dh-stage-argo.yaml
  manifests/overlays/prod/applications/data_hub/dh-stage-jupyterhub.yaml
  manifests/overlays/prod/applications/data_hub/dh-stage-kafka.yaml
Labels: size/S

#121 Update inclusions list
  manifests/overlays/prod/configs/argo_cm/resource.inclusions
Labels: approved, do-not-merge/hold, size/L

#122 Add OCP 4.5 cluster spec and update inclusion list.
  manifests/overlays/prod/configs/argo_cm/resource.inclusions
  manifests/overlays/prod/secrets/clusters/api.ocp4.prod.psi.redhat.com.enc.yaml
Labels: approved, size/M

#123 Remove aicoe namespace
  manifests/overlays/prod/secrets/clusters/api.ocp4.prod.psi.redhat.com.enc.yaml
Labels: size/S

#124 include thoth-station stage package-update application
  manifests/overlays/prod/applications/thoth-station/kustomization.yaml
  manifests/overlays/prod/applications/thoth-station/stage/stage-thoth-package-update.yaml
Labels: approved, size/S

#125 graph-sync ignore auto labels in-sync on specific file
  manifests/overlays/prod/applications/thoth-station/stage/stage-thoth-graph-sync-backend.yaml
  manifests/overlays/prod/applications/thoth-station/stage/stage-thoth-graph-sync-middletier.yaml
Labels: approved, size/S

#127 Revert "patch up duplicate inclusions of same kind"
  manifests/overlays/prod/configs/argo_cm/resource.inclusions
Labels: approved, size/S

#129 Add ns to kustomization
  manifests/overlays/prod/secrets/clusters/secret-generator.yaml
Labels: approved, size/XS

#131 move aicoe-ci from ocp to ocp4 cluster.
  manifests/overlays/prod/applications/thoth-station/bots/aicoe-ci.yaml
Labels: approved, size/XS

#132 patch up duplicate inclusions of same kind
  manifests/overlays/prod/configs/argo_cm/resource.inclusions
Labels: approved, size/S
