Repository AICoE/aicoe-cd, pull requests merged in 2020-04, with the labels that each got.

#2 Add argocd deployment playbook and assets
  Pipfile
  Pipfile.lock
  README.md
  manifests/argocd-cm.yaml
  objects/admin_creds_patch.yaml
  objects/argocd_server_route.yaml
  objects/namespace-install.yaml
  objects/secret.yaml
  playbook.yaml
  scratch/argocd-repo-server_scratch.yaml
  vars/common-vars.yaml
  vars/dev-vars.yaml
  vars/gpg-keys/dev-key.yaml
  vars/gpg-keys/prod-key.yaml
  vars/prod-vars.yaml
Labels: size/XXL

#4 Add plugin flag to dev-vars
  vars/dev-vars.yaml
Labels: size/XS

#5 Add prod key
  vars/gpg-keys/prod-key.yaml
Labels: approved, size/L

#8 Fix Lint Errors in README
  README.md
Labels: size/M

#9 Update admin creds
  vars/dev-vars.yaml
  vars/prod-vars.yaml
Labels: approved, size/XS

#7 Add a flag to ignore cluster objects
  README.md
  objects/namespace-install.yaml
  playbook.yaml
Labels: approved, size/S
