Repository AICoE/aicoe-cd, pull requests merged in 2020-06, with the labels that each got.

#26 Remove namespace that no long exists
  vars/prod-vars.yaml
Labels: approved, size/XS

#27 Add label to permit monitoring
  objects/patches/argocd_metrics_service_patch.yaml
  objects/patches/argocd_server_metrics_service_patch.yaml
Labels: approved, size/S

#25 Add slis
  README.md
  RUNBOOK.md
  docs/README.md
  docs/application_management.md
  docs/argocd_metrics.md
  docs/argocd_permissions.md
  docs/cluster_ns_management.md
  docs/secret_management.md
Labels: size/L

#30 Increase memory for app-controller
  objects/namespace-install.yaml
Labels: approved, size/XS

#32 Add aicoe-sre repo
  vars/prod-vars.yaml
Labels: approved, size/XS

#33 Remove ns that no longer exists
  vars/prod-vars.yaml
Labels: approved, size/XS

#34 Replace test prod with actual in spec
  vars/prod-vars.yaml
Labels: approved, size/XS

#35 Add AICoE Monitor
  vars/prod-vars.yaml
Labels: size/XS

#37 Remove PSI Monitoring Namespace
  vars/prod-vars.yaml
Labels: size/XS

#38 Add dh ocp4 spec
  vars/prod-vars.yaml
Labels: approved, size/M

#39 Remove dh ocp4 spec
  vars/prod-vars.yaml
Labels: size/M

#36 Add applications declaritively
  docs/README.md
  docs/application_management.md
  objects/applications/data_hub/dh-prod-jupyterhub.yaml
  objects/applications/data_hub/dh-psi-monitoring.yaml
  objects/applications/data_hub/dh-stage-jupyterhub.yaml
  playbook.yaml
Labels: approved, size/L

#40 Replace route retrieval method
  playbook.yaml
Labels: approved

#42 Add JH prod Argocd App
  objects/applications/data_hub/dh-prod-jupyterhub.yaml
Labels: approved

#44 Update the ksops docs
  docs/secret_management.md
Labels: size/L
