Repository AICoE/aicoe-cd, pull requests merged in 2020-07, with the labels that each got.

#48 enable pre-commit support for the application
  .yamllint
  .zuul.yaml
  objects/clusters.yaml
  objects/patches/admin_creds_patch.yaml
Labels: approved, size/S

#45 Add dh-stage-argo namespace with Argo and Argo events apps
  objects/applications/data_hub/dh-stage-argo.yaml
  vars/prod-vars.yaml
Labels: approved, size/M

#52 Incrase memory for app controller
  objects/namespace-install.yaml
Labels: approved, size/XS

#51 Rename Argo and Argo Events to respect the convention
  objects/applications/data_hub/dh-stage-argo.yaml
Labels: approved, size/XS

#53 Add SrcOps token to access private repos
  docs/application_management.md
  objects/srcops-secret.yaml
  playbook.yaml
  vars/common-vars.yaml
Labels: approved, size/M

#54 Fix base64 encoding on srcops secret
  objects/srcops-secret.yaml
Labels: approved, size/XS

#55 Stop non-admin ArgoCD users from creating applications via UI
  objects/projects/projects.yaml
  vars/prod-vars.yaml
Labels: approved, size/S

#57 include aicoe-ci configuration file
  .aicoe-ci.yaml
Labels: approved, size/XS

#56 ArgoCD to 1.61
  Dockerfile
  README.md
  docs/README.md
  docs/version.md
  objects/namespace-install.yaml
  objects/patches/argocd_dex_dc_patch.yaml
  playbook.yaml
  scratch/argocd-repo-server_scratch.yaml
  vars/dev-vars.yaml
  vars/prod-vars.yaml
Labels: approved, size/L

#58 Correct image tag
  vars/dev-vars.yaml
  vars/prod-vars.yaml
Labels: approved, size/XS
