Repository AICoE/aicoe-cd, pull requests merged in 2020-05, with the labels that each got.

#10 Add openshift authentication
  objects/namespace-install.yaml
  objects/patches/admin_creds_patch.yaml
  objects/patches/argocd_cm_patch.yaml
  objects/patches/argocd_dex_dc_patch.yaml
  objects/patches/argocd_dex_sa_patch.yaml
  playbook.yaml
  vars/prod-vars.yaml
Labels: approved, size/L

#11 Initial Commit for Runbook
  RUNBOOK.md
Labels: size/S

#12 Add RBAC restrictions
  objects/patches/argocd_rbac_cm_patch.yaml
  objects/projects/projects.yaml
  playbook.yaml
  vars/prod-vars.yaml
Labels: approved, size/M

#13 Apply flag to project
  README.md
  objects/namespace-install.yaml
  playbook.yaml
Labels: approved, size/S

#14 Update tekton exclusion apigroup
  vars/prod-vars.yaml
Labels: approved, size/XS

#15 Add Instructions for application deployment
  README.md
Labels: size/M

#17 Add anishasthana and HumairAK to Owners
  .github/CODEOWNERS
Labels: approved, size/XS

#16 Add cluster spec & exclusions
  .coafile
  examples/argocd-manager-rolebinding.yaml
  objects/clusters.yaml
  objects/patches/argocd_dex_dc_patch.yaml
  objects/projects/projects.yaml
  playbook.yaml
  vars/dev-vars.yaml
  vars/prod-vars.yaml
Labels: approved, size/L

#18 Add docs
  README.md
  docs/README.md
  docs/application_management.md
  docs/argocd_permissions.md
  docs/cluster_ns_management.md
  docs/secret_management.md
Labels: size/L

#20 Add inclusions
  RUNBOOK.md
  docs/cluster_ns_management.md
  vars/prod-vars.yaml
Labels: approved, size/L

#21 Include thoth sub cluster
  vars/prod-vars.yaml
Labels: approved, size/XS

#22 add aicoe-aiops-devops group and perms
  docs/argocd_permissions.md
  vars/prod-vars.yaml
Labels: size/S

#23 Add aiops project to vcs
  objects/projects/projects.yaml
Labels: approved, size/S
