Repository AICoE/aicoe-cd, pull requests merged in 2020-12, with the labels that each got.

#191 feat: Add argocd-admin role with access to apps, make template role read only
  manifests/overlays/prod/configs/argo_rbac_cm/policy.csv
Labels: approved, size/M

#190 feat(ccx): Add insights rules statistics app
  manifests/overlays/prod/applications/ccx/insights-rules-statistics.yaml
  manifests/overlays/prod/applications/ccx/kustomization.yaml
  manifests/overlays/prod/configs/argo_cm/repositories
Labels: approved, size/S

#193 fix: Internal gitlab cert issue
  manifests/overlays/prod/configs/argo_cm/repositories
Labels: approved, size/XS

#194 Add Stage and Production Superset apps
  manifests/overlays/prod/applications/data_hub/dh-prod-superset.yaml
  manifests/overlays/prod/applications/data_hub/dh-stage-superset.yaml
  manifests/overlays/prod/applications/data_hub/kustomization.yaml
  manifests/overlays/prod/secrets/clusters/datahub.psi.redhat.com.enc.yaml
  manifests/overlays/prod/secrets/clusters/paas.stage.psi.redhat.com.enc.yaml
Labels: approved, size/M

#192 support deployment of thoth app graph-schema-update with argo
  manifests/overlays/prod/applications/thoth-station/ocp4-stage/kustomization.yaml
  manifests/overlays/prod/applications/thoth-station/ocp4-stage/stage-thoth-graph-schema-update.yaml
Labels: approved, size/S

#195 fix: Add missing dex groups
  manifests/overlays/prod/configs/argo_cm/dex.config
Labels: approved, size/XS

#196 Restructure ArgoCD app to improve sync performance
  .github/CODEOWNERS
  OWNERS
  manifests/overlays/prod/applications/argocd/aicoe-argocd.yaml
  manifests/overlays/prod/applications/argocd/argocd-apps.yaml
  manifests/overlays/prod/applications/argocd/kustomization.yaml
  manifests/overlays/prod/applications/data_hub/kustomization.yaml
  manifests/overlays/prod/kustomization.yaml
Labels: approved, size/M

#197 Turn off autosync for argocd
  manifests/overlays/prod/applications/argocd/aicoe-argocd.yaml
Labels: approved, size/XS

#198 Update dex server init container image
  manifests/overlays/prod/applications/argocd/aicoe-argocd.yaml
  manifests/overlays/prod/deployments/argocd-dex-server_patch.yaml
  manifests/overlays/prod/kustomization.yaml
Labels: approved, size/S

#199 Fix typo that was removing container spec for dex
  manifests/overlays/prod/deployments/argocd-dex-server_patch.yaml
Labels: approved, size/XS

#200 Remove 3.11 Rsyslog app from ArgoCD
  manifests/overlays/prod/applications/data_hub/dh-prod-rsyslog.yaml
  manifests/overlays/prod/applications/data_hub/kustomization.yaml
Labels: approved, size/S

#201 Rename rsyslog app name for consistency
  manifests/overlays/prod/applications/data_hub/dh-prod-rsyslog.yaml
  manifests/overlays/prod/applications/data_hub/kustomization.yaml
Labels: approved, size/XS

#202 Remove Prometheus Service Monitor from ArgoCD app
  manifests/overlays/prod/kustomization.yaml
  manifests/overlays/prod/monitoring/argocd-service-monitor.yaml
  manifests/overlays/prod/monitoring/kustomization.yaml
Labels: approved, size/S
