Repository AICoE/aicoe-cd, pull requests merged in 2020-08, with the labels that each got.

#59 thoth-station application manifest that is to be handled by argo
  objects/applications/thoth-station/stage/stage-thoth-chat-notification.yaml
  objects/applications/thoth-station/test/test-amun.yaml
  objects/applications/thoth-station/test/test-thoth-advise-reporter.yaml
  objects/applications/thoth-station/test/test-thoth-adviser.yaml
  objects/applications/thoth-station/test/test-thoth-cve-update.yaml
  objects/applications/thoth-station/test/test-thoth-graph-sync.yaml
  objects/applications/thoth-station/test/test-thoth-investigator.yaml
  objects/applications/thoth-station/test/test-thoth-kebechet.yaml
  objects/applications/thoth-station/test/test-thoth-management-api.yaml
  objects/applications/thoth-station/test/test-thoth-metrics-exporter.yaml
  objects/applications/thoth-station/test/test-thoth-mi-scheduler.yaml
  objects/applications/thoth-station/test/test-thoth-package-extract.yaml
  objects/applications/thoth-station/test/test-thoth-package-update.yaml
  objects/applications/thoth-station/test/test-thoth-security-indicators.yaml
  objects/applications/thoth-station/test/test-thoth-slo-reporter.yaml
  objects/applications/thoth-station/test/test-thoth-solver.yaml
  objects/applications/thoth-station/test/test-thoth-user-api.yaml
Labels: approved, size/L

#43 added a few STAGE environment applications
  objects/applications/thoth-station/stage/core-backend.yaml
  objects/applications/thoth-station/stage/core-frontend.yaml
  objects/applications/thoth-station/stage/core-graph.yaml
  objects/applications/thoth-station/stage/core-infra.yaml
  objects/applications/thoth-station/stage/core-middletier.yaml
  objects/applications/thoth-station/stage/user-api.yaml
Labels: approved, size/L

#60 Add ArgoCD Application
  objects/applications/data_hub/aicoe-argocd.yaml
  vars/prod-vars.yaml
Labels: approved, size/S

#63 Add ArgoCD namespace to cluster spec
  vars/prod-vars.yaml
Labels: approved, size/XS

#65 Add cd repo
  manifests/overlays/prod/resources/configs/argo_cm/repositories
Labels: approved, size/XS

#66 Kustomize argocd
  manifests/overlays/prod/privileged_resources/applications/data_hub/aicoe-argocd.yaml
  manifests/overlays/prod/privileged_resources/applications/thoth-station/stage/core-backend.yaml
  manifests/overlays/prod/privileged_resources/applications/thoth-station/stage/core-frontend.yaml
  manifests/overlays/prod/privileged_resources/applications/thoth-station/stage/core-graph.yaml
  manifests/overlays/prod/privileged_resources/applications/thoth-station/stage/core-infra.yaml
  manifests/overlays/prod/privileged_resources/applications/thoth-station/stage/core-middletier.yaml
  manifests/overlays/prod/privileged_resources/applications/thoth-station/stage/user-api.yaml
Labels: approved, size/L

#67 Add argocd resources to prod kustomization
  .pre-commit-config.yaml
  .yamllint
  README.md
  manifests/overlays/prod/kustomization.yaml
  manifests/overlays/prod/resources/secrets/clusters/apps.ocp.prod.psi.redhat.com.enc.yaml
Labels: approved, size/S

#68 Add aggregation to admin for projects/apps
  manifests/crds/aggregate-to-admin.yaml
  manifests/crds/kustomization.yaml
Labels: approved, size/S

#69 Add proj/apps to inclusions list
  vars/prod-vars.yaml
Labels: approved, size/XS

#71 Add aiops-prod-argo
  objects/applications/aiops/aiops-prod-argo.yaml
  vars/prod-vars.yaml
Labels: approved, size/M

#70 Add apps/projs to inclusions list
  README.md
  manifests/overlays/prod/resources/configs/argo_cm/resource.inclusions
Labels: approved, size/S

#72 Merge aiops-prod-argo to kustomize
  manifests/overlays/prod/privileged_resources/applications/aiops/aiops-prod-argo.yaml
  manifests/overlays/prod/resources/secrets/clusters/apps.ocp.prod.psi.redhat.com.enc.yaml
Labels: approved, size/M

#74 Remove aiops-argo-prod from namespaces
  vars/prod-vars.yaml
Labels: approved, size/XS

#75 Update service account name for dex-server
  manifests/overlays/prod/resources/configs/argo_cm/dex.config
  manifests/overlays/prod/resources/secrets/clusters/apps.ocp.prod.psi.redhat.com.enc.yaml
Labels: approved, size/XS

#78 Update revision for argocd app
  manifests/overlays/prod/applications/data_hub/aicoe-argocd.yaml
Labels: approved, size/XS

#79 Add aicoe, aicoe-prod-bots ns to ocp4
  manifests/overlays/prod/secrets/clusters/apps.ocp.prod.psi.redhat.com.enc.yaml
Labels: size/XS

#80 Add dev odh project
  manifests/overlays/prod/applications/data_hub/aicoe-argocd.yaml
  manifests/overlays/prod/configs/argo_rbac_cm/policy.csv
  manifests/overlays/prod/projects/projects.yaml
  manifests/overlays/prod/secrets/clusters/api.aasthana.dev.datahub.redhat.com.enc.yaml
Labels: approved, size/M

#81 Update doc links to work with mkdocs
  docs/admin/add_namespace_to_cluster.md
  docs/argocd_project_permissions.md
  docs/create_argocd_application_manifest.md
  docs/get_argocd_to_manage_your_app.md
  docs/give_argocd_access_to_your_project.md
  docs/inclusions_explained.md
  examples/argocd-manager-rolebinding.yaml
Labels: approved, size/S

#49 Add AI-Ops analytics project - Openshift SME
  manifests/overlays/dev/secrets/auth/secret-generator.yaml
  manifests/overlays/dev/secrets/auth/srcops.enc.yaml
  manifests/overlays/prod/applications/aiops/argo-analytics.yaml
  manifests/overlays/prod/configs/argo_cm/repositories
  manifests/overlays/prod/secrets/auth/secret-generator.yaml
  manifests/overlays/prod/secrets/auth/srcops.enc.yaml
Labels: approved, size/M

#82 Fix listing of AI-Ops applications in kustomization.yaml file
  manifests/overlays/prod/applications/aiops/kustomization.yaml
Labels: approved, size/XS

#83 Add ArgoCD app to kustomization file
  manifests/overlays/prod/applications/data_hub/kustomization.yaml
Labels: approved, size/XS

#84 Use correct sesheta token
  manifests/overlays/dev/secrets/auth/srcops.enc.yaml
  manifests/overlays/prod/secrets/auth/srcops.enc.yaml
Labels: approved, size/M

#86 update thoth-station applications in the kustomize file
  manifests/overlays/prod/applications/thoth-station/kustomization.yaml
Labels: approved, size/S

#88 include more thoth-station applications
  manifests/overlays/prod/applications/thoth-station/bots/thoth-nepthys.yaml
  manifests/overlays/prod/applications/thoth-station/bots/thoth-qeb-hwt.yaml
  manifests/overlays/prod/applications/thoth-station/bots/thoth-sefkhet-abwy.yaml
  manifests/overlays/prod/applications/thoth-station/kustomization.yaml
  manifests/overlays/prod/applications/thoth-station/stage/stage-amun.yaml
  manifests/overlays/prod/applications/thoth-station/stage/stage-thoth-amun-api.yaml
  manifests/overlays/prod/applications/thoth-station/stage/stage-thoth-amun-inspection.yaml
  manifests/overlays/prod/applications/thoth-station/stage/stage-thoth-graph-refresh.yaml
  manifests/overlays/prod/applications/thoth-station/stage/stage-thoth-kebechet.yaml
  manifests/overlays/prod/applications/thoth-station/stage/stage-thoth-revsolver.yaml
  manifests/overlays/prod/applications/thoth-station/test/core-test.yaml
  manifests/overlays/prod/applications/thoth-station/test/test-thoth-chat-notification.yaml
  manifests/overlays/prod/applications/thoth-station/test/test-thoth-graph-refresh.yaml
  manifests/overlays/prod/applications/thoth-station/test/test-thoth-revsolver.yaml
Labels: approved, size/L

#89 Update applications
  manifests/overlays/prod/applications/aiops/aiops-prod-argo.yaml
  manifests/overlays/prod/applications/data_hub/dh-prod-jupyterhub.yaml
  manifests/overlays/prod/applications/data_hub/dh-psi-monitoring.yaml
  manifests/overlays/prod/applications/data_hub/dh-stage-argo.yaml
  manifests/overlays/prod/applications/data_hub/dh-stage-jupyterhub.yaml
  manifests/overlays/prod/configs/argo_cm/repositories
Labels: approved, size/M

#91 Add helm plugin and configuration to argocd
  Dockerfile
  manifests/base/resources/deployments/argocd-repo-server_patch.yaml
  manifests/overlays/dev/configs/argo_cm/configManagementPlugins
  manifests/overlays/dev/kustomization.yaml
  manifests/overlays/prod/configs/argo_cm/configManagementPlugins
  manifests/overlays/prod/kustomization.yaml
Labels: approved, do-not-merge/hold, size/M

#92 Add Stage Kafka Namespace
  manifests/overlays/prod/secrets/clusters/paas.stage.psi.redhat.com.enc.yaml
Labels: approved, size/XS

#93 Add Stage Kafka Application
  manifests/overlays/prod/applications/data_hub/dh-stage-kafka.yaml
Labels: approved, size/S

#94 Add kafka app yaml
  manifests/overlays/prod/applications/data_hub/kustomization.yaml
Labels: approved, size/XS

#95 Update sops version
  Dockerfile
Labels: approved, size/XS

#96 Update ArgoCD deployment image
  manifests/base/resources/deployments/argocd-repo-server_patch.yaml
Labels: approved, size/XS

#97 Add inclusion for kafka resources
  manifests/overlays/prod/configs/argo_cm/resource.inclusions
Labels: approved, size/XS
