Repository AICoE/aicoe-cd, pull requests merged in 2020-10, with the labels that each got.

#133 Add data hub stage rsyslog deployment
  manifests/overlays/prod/applications/data_hub/dh-stage-rsyslog.yaml
  manifests/overlays/prod/applications/data_hub/kustomization.yaml
  manifests/overlays/prod/configs/argo_cm/repositories
  manifests/overlays/prod/secrets/clusters/paas.stage.psi.redhat.com.enc.yaml
Labels: approved, size/M

#138 Add application manifest for data hub production rsyslog
  manifests/overlays/prod/applications/data_hub/dh-prod-rsyslog.yaml
  manifests/overlays/prod/applications/data_hub/kustomization.yaml
  manifests/overlays/prod/secrets/clusters/datahub.psi.redhat.com.enc.yaml
Labels: approved, do-not-merge/hold, size/S

#136 include thoth-station stage slo-reporter application
  manifests/overlays/prod/applications/thoth-station/kustomization.yaml
  manifests/overlays/prod/applications/thoth-station/stage/stage-thoth-slo-reporter.yaml
Labels: approved, size/S

#139 Update argocd revision
  examples/configure_development.sh
  manifests/base/kustomization.yaml
  manifests/overlays/prod/configs/argo_cm/dex.config
  manifests/overlays/prod/serviceaccounts/argocd-dex-server.yaml
Labels: approved, do-not-merge/hold, size/M

#140 Fix dex server sa redirect annotations
  manifests/overlays/prod/serviceaccounts/argocd-dex-server.yaml
Labels: approved, size/XS

#141 Update url for new cluster
  docs/index.md
  manifests/overlays/prod/configs/argo_cm/url
Labels: approved, do-not-merge/hold, size/XS

#142 Add more memory to app controller
  manifests/overlays/prod/deployments/argocd-application-controller_patch.yaml
  manifests/overlays/prod/kustomization.yaml
Labels: approved, size/S

#143 Update argocd cluster destination
  manifests/overlays/prod/applications/data_hub/aicoe-argocd.yaml
  manifests/overlays/prod/configs/argo_cm/resource.inclusions
Labels: approved, do-not-merge/hold, size/XS

#144 Remove Argo and Argo events from DH Stage cluster
  manifests/overlays/prod/applications/data_hub/dh-stage-argo.yaml
  manifests/overlays/prod/applications/data_hub/kustomization.yaml
  manifests/overlays/prod/secrets/clusters/paas.stage.psi.redhat.com.enc.yaml
Labels: approved, size/M

#145 Add dh-psi-monitoring namespace
  manifests/overlays/prod/secrets/clusters/apps.ocp.prod.psi.redhat.com.enc.yaml
Labels: approved, size/XS

#146 Update cluster for dh-psi-monitoring
  manifests/overlays/prod/applications/data_hub/dh-psi-monitoring.yaml
Labels: size/XS

#147 Add prometheus and grafana to inclusions for ocp4
  manifests/overlays/prod/configs/argo_cm/resource.inclusions
Labels: approved, size/XS

#148 Add dh-psi-monitoring to new ocp4 cluster
  manifests/overlays/prod/secrets/clusters/api.ocp4.prod.psi.redhat.com.enc.yaml
Labels: approved, size/XS

#149 include thoth-station qeb-hwt stage and test application
  manifests/overlays/prod/applications/thoth-station/kustomization.yaml
  manifests/overlays/prod/applications/thoth-station/stage/stage-thoth-qeb-hwt.yaml
  manifests/overlays/prod/applications/thoth-station/test/test-thoth-qeb-hwt.yaml
Labels: approved, size/M

#150 disable thoth bot qebhwt deployment
  manifests/overlays/prod/applications/thoth-station/kustomization.yaml
Labels: approved, size/XS

#152 removed thoth-dev namespace that no longer exists
  manifests/overlays/prod/secrets/clusters/api.ocp4.prod.psi.redhat.com.enc.yaml
  manifests/overlays/prod/secrets/clusters/apps.ocp.prod.psi.redhat.com.enc.yaml
Labels: size/XS

#154 Fix mac change issue with cluster specs
  manifests/overlays/prod/secrets/clusters/api.ocp4.prod.psi.redhat.com.enc.yaml
  manifests/overlays/prod/secrets/clusters/apps.ocp.prod.psi.redhat.com.enc.yaml
Labels: size/M

#155 Aiops prod argo ocp4
  manifests/overlays/prod/applications/aiops/aiops-prod-argo.yaml
  manifests/overlays/prod/applications/aiops/argo-analytics.yaml
  manifests/overlays/prod/configs/argo_cm/resource.inclusions
  manifests/overlays/prod/secrets/clusters/api.ocp4.prod.psi.redhat.com.enc.yaml
Labels: approved, size/M

#157 Update sa token for old ocp4 cluster
  manifests/overlays/prod/secrets/clusters/apps.ocp.prod.psi.redhat.com.enc.yaml
Labels: size/S

#158 Deploy rsyslog on ocp4 cluster
  manifests/overlays/prod/applications/data_hub/dh-prod-rsyslog-ocp4.yaml
  manifests/overlays/prod/secrets/clusters/api.ocp4.prod.psi.redhat.com.enc.yaml
Labels: approved, size/S

#159 Add Rsyslog application to application list
  manifests/overlays/prod/applications/data_hub/dh-prod-rsyslog-ocp4.yaml
  manifests/overlays/prod/applications/data_hub/kustomization.yaml
Labels: size/XS

#160 Update prom/grafana repo locations
  manifests/overlays/prod/applications/data_hub/dh-psi-monitoring.yaml
Labels: approved, size/S

#161 Add ignoredifference for annotation on secret
  manifests/overlays/prod/applications/data_hub/dh-psi-monitoring.yaml
Labels: approved, size/XS

#162 Revert annotation diff ignore for dh monitoring app
  manifests/overlays/prod/applications/data_hub/dh-psi-monitoring.yaml
Labels: approved, size/XS

#164 Update inclusions list with kaizen cluster
  manifests/overlays/prod/configs/argo_cm/resource.inclusions
Labels: size/M

#163 update kaizen moc cluster secrets for argocd
  manifests/overlays/prod/secrets/clusters/k-openshift.osh.massopen.cloud.enc.yaml
  manifests/overlays/prod/secrets/clusters/secret-generator.yaml
Labels: size/M

#165 Update operate 1st base revision
  manifests/base/kustomization.yaml
Labels: approved, do-not-merge/hold, size/XS
