Repository AICoE/aicoe-cd, pull requests merged in 2020-11, with the labels that each got.

#166 Add ocp4 anomaly detection.
  manifests/overlays/prod/applications/aiops/argo-anomaly.yaml
  manifests/overlays/prod/applications/aiops/kustomization.yaml
  manifests/overlays/prod/configs/argo_cm/repositories
Labels: approved, size/S

#167 Add Thoth Devops Key to ArgoCD
  manifests/overlays/prod/secrets/gpg/secret.enc.yaml
Labels: approved, size/XS

#168 Remove deleted thoth namespaces
  manifests/overlays/prod/secrets/clusters/api.ocp4.prod.psi.redhat.com.enc.yaml
  manifests/overlays/prod/secrets/clusters/apps.ocp.prod.psi.redhat.com.enc.yaml
Labels: size/S

#170 Update Thoth Key
  manifests/overlays/prod/secrets/gpg/secret.enc.yaml
Labels: approved, size/XS

#172 Update images to use the quay custom image
  manifests/overlays/prod/deployments/argocd-application-controller_patch.yaml
  manifests/overlays/prod/deployments/argocd-server_patch.yaml
  manifests/overlays/prod/kustomization.yaml
Labels: approved, size/S

#173 Remove nonexistent resources from 3.11 inclusions list
  manifests/overlays/prod/configs/argo_cm/resource.inclusions
Labels: approved, size/XS

#174 Updated runbook w/ instructions to handle rbac issues
  RUNBOOK.md
Labels: approved, size/S

#176 Add data-catalog namespace for ArgoCD to manange
  manifests/overlays/prod/applications/data_hub/dh-prod-analytics-factory.yaml
  manifests/overlays/prod/applications/data_hub/dh-prod-customer-journeys.yaml
  manifests/overlays/prod/applications/data_hub/dh-prod-data-catalog-ccx.yaml
  manifests/overlays/prod/applications/data_hub/dh-prod-data-catalog-usir.yaml
  manifests/overlays/prod/applications/data_hub/dh-stage-analytics-factory.yaml
  manifests/overlays/prod/secrets/clusters/datahub.psi.redhat.com.enc.yaml
  manifests/overlays/prod/secrets/clusters/paas.stage.psi.redhat.com.enc.yaml
Labels: approved, size/M

#177 Add datacatalog namespaces to kustomization.yaml
  manifests/overlays/prod/applications/data_hub/kustomization.yaml
Labels: approved, do-not-merge/hold, size/XS

#179 Turn off auto-sync for dh-stage-analytics-factory
  manifests/overlays/prod/applications/data_hub/dh-stage-analytics-factory.yaml
Labels: approved, size/XS

#180 Add ArgoCD Service Monitor
  manifests/overlays/prod/kustomization.yaml
  manifests/overlays/prod/monitoring/argocd-service-monitor.yaml
  manifests/overlays/prod/monitoring/kustomization.yaml
Labels: size/S

#181 Add metadata.name to ArgoCD Service Monitor
  manifests/overlays/prod/monitoring/argocd-service-monitor.yaml
Labels: approved, size/XS

#182 Fix ArgoCD service monitor name
  manifests/overlays/prod/monitoring/argocd-service-monitor.yaml
Labels: approved, size/XS

#178 Support Thoth ocp4 stage deployment
  manifests/overlays/prod/applications/thoth-station/kustomization.yaml
  manifests/overlays/prod/applications/thoth-station/ocp4-stage/core-backend.yaml
  manifests/overlays/prod/applications/thoth-station/ocp4-stage/core-frontend.yaml
  manifests/overlays/prod/applications/thoth-station/ocp4-stage/core-graph.yaml
  manifests/overlays/prod/applications/thoth-station/ocp4-stage/core-infra.yaml
  manifests/overlays/prod/applications/thoth-station/ocp4-stage/core-middletier.yaml
  manifests/overlays/prod/applications/thoth-station/ocp4-stage/kustomization.yaml
  manifests/overlays/prod/applications/thoth-station/ocp4-stage/stage-thoth-advise-reporter.yaml
  manifests/overlays/prod/applications/thoth-station/ocp4-stage/stage-thoth-adviser.yaml
  manifests/overlays/prod/applications/thoth-station/ocp4-stage/stage-thoth-amun-api.yaml
  manifests/overlays/prod/applications/thoth-station/ocp4-stage/stage-thoth-amun-inspection.yaml
  manifests/overlays/prod/applications/thoth-station/ocp4-stage/stage-thoth-chat-notification.yaml
  manifests/overlays/prod/applications/thoth-station/ocp4-stage/stage-thoth-cve-update.yaml
  manifests/overlays/prod/applications/thoth-station/ocp4-stage/stage-thoth-graph-backup.yaml
  manifests/overlays/prod/applications/thoth-station/ocp4-stage/stage-thoth-graph-refresh.yaml
  manifests/overlays/prod/applications/thoth-station/ocp4-stage/stage-thoth-graph-sync-backend.yaml
  manifests/overlays/prod/applications/thoth-station/ocp4-stage/stage-thoth-graph-sync-middletier.yaml
  manifests/overlays/prod/applications/thoth-station/ocp4-stage/stage-thoth-investigator.yaml
  manifests/overlays/prod/applications/thoth-station/ocp4-stage/stage-thoth-kebechet.yaml
  manifests/overlays/prod/applications/thoth-station/ocp4-stage/stage-thoth-management-api.yaml
  manifests/overlays/prod/applications/thoth-station/ocp4-stage/stage-thoth-metrics-exporter.yaml
  manifests/overlays/prod/applications/thoth-station/ocp4-stage/stage-thoth-mi.yaml
  manifests/overlays/prod/applications/thoth-station/ocp4-stage/stage-thoth-package-extract.yaml
  manifests/overlays/prod/applications/thoth-station/ocp4-stage/stage-thoth-package-releases.yaml
  manifests/overlays/prod/applications/thoth-station/ocp4-stage/stage-thoth-package-update.yaml
  manifests/overlays/prod/applications/thoth-station/ocp4-stage/stage-thoth-qeb-hwt.yaml
  manifests/overlays/prod/applications/thoth-station/ocp4-stage/stage-thoth-revsolver.yaml
  manifests/overlays/prod/applications/thoth-station/ocp4-stage/stage-thoth-security-indicators.yaml
  manifests/overlays/prod/applications/thoth-station/ocp4-stage/stage-thoth-slo-reporter.yaml
  manifests/overlays/prod/applications/thoth-station/ocp4-stage/stage-thoth-solver.yaml
  manifests/overlays/prod/applications/thoth-station/ocp4-stage/stage-thoth-user-api.yaml
  manifests/overlays/prod/configs/argo_rbac_cm/policy.csv
  manifests/overlays/prod/projects/projects.yaml
Labels: approved, size/XL

#183 fix the thoth-station ocp4 deployment with standard ids
  manifests/overlays/prod/applications/thoth-station/ocp4-stage/core-backend.yaml
  manifests/overlays/prod/applications/thoth-station/ocp4-stage/core-frontend.yaml
  manifests/overlays/prod/applications/thoth-station/ocp4-stage/core-graph.yaml
  manifests/overlays/prod/applications/thoth-station/ocp4-stage/core-infra.yaml
  manifests/overlays/prod/applications/thoth-station/ocp4-stage/core-middletier.yaml
  manifests/overlays/prod/applications/thoth-station/ocp4-stage/stage-thoth-advise-reporter.yaml
  manifests/overlays/prod/applications/thoth-station/ocp4-stage/stage-thoth-adviser.yaml
  manifests/overlays/prod/applications/thoth-station/ocp4-stage/stage-thoth-amun-api.yaml
  manifests/overlays/prod/applications/thoth-station/ocp4-stage/stage-thoth-amun-inspection.yaml
  manifests/overlays/prod/applications/thoth-station/ocp4-stage/stage-thoth-chat-notification.yaml
  manifests/overlays/prod/applications/thoth-station/ocp4-stage/stage-thoth-cve-update.yaml
  manifests/overlays/prod/applications/thoth-station/ocp4-stage/stage-thoth-graph-backup.yaml
  manifests/overlays/prod/applications/thoth-station/ocp4-stage/stage-thoth-graph-refresh.yaml
  manifests/overlays/prod/applications/thoth-station/ocp4-stage/stage-thoth-graph-sync-backend.yaml
  manifests/overlays/prod/applications/thoth-station/ocp4-stage/stage-thoth-graph-sync-middletier.yaml
  manifests/overlays/prod/applications/thoth-station/ocp4-stage/stage-thoth-investigator.yaml
  manifests/overlays/prod/applications/thoth-station/ocp4-stage/stage-thoth-kebechet.yaml
  manifests/overlays/prod/applications/thoth-station/ocp4-stage/stage-thoth-management-api.yaml
  manifests/overlays/prod/applications/thoth-station/ocp4-stage/stage-thoth-metrics-exporter.yaml
  manifests/overlays/prod/applications/thoth-station/ocp4-stage/stage-thoth-mi.yaml
  manifests/overlays/prod/applications/thoth-station/ocp4-stage/stage-thoth-package-extract.yaml
  manifests/overlays/prod/applications/thoth-station/ocp4-stage/stage-thoth-package-releases.yaml
  manifests/overlays/prod/applications/thoth-station/ocp4-stage/stage-thoth-package-update.yaml
  manifests/overlays/prod/applications/thoth-station/ocp4-stage/stage-thoth-qeb-hwt.yaml
  manifests/overlays/prod/applications/thoth-station/ocp4-stage/stage-thoth-revsolver.yaml
  manifests/overlays/prod/applications/thoth-station/ocp4-stage/stage-thoth-security-indicators.yaml
  manifests/overlays/prod/applications/thoth-station/ocp4-stage/stage-thoth-slo-reporter.yaml
  manifests/overlays/prod/applications/thoth-station/ocp4-stage/stage-thoth-solver.yaml
  manifests/overlays/prod/applications/thoth-station/ocp4-stage/stage-thoth-user-api.yaml
Labels: approved, size/M

#184 Removed deleted resource from stage psi cluster
  manifests/overlays/prod/configs/argo_cm/resource.inclusions
Labels: size/XS

#185 Add Gfrasca dev cluster to included resources
  manifests/overlays/prod/configs/argo_cm/resource.inclusions
Labels: approved, size/XS

#186 Add Logstash Applications
  manifests/overlays/prod/applications/data_hub/dh-prod-logstash.yaml
  manifests/overlays/prod/applications/data_hub/dh-stage-logstash.yaml
  manifests/overlays/prod/applications/data_hub/kustomization.yaml
Labels: approved, size/M

#187 Fix typo in dh-stage-logstash resource kustomization
  manifests/overlays/prod/applications/data_hub/kustomization.yaml
Labels: approved, size/XS

#188 Change redis repo to quay
  manifests/overlays/prod/deployments/argocd-redis_patch.yaml
  manifests/overlays/prod/kustomization.yaml
Labels: size/S
