Repository AICoE/aicoe-cd, pull requests merged in 2021-12, with the labels that each got.

#737 Add dh-prod-superset manifest to psi ocp4
  manifests/overlays/prod/applications/data_hub/dh-prod-superset.ocp4.yaml
  manifests/overlays/prod/applications/data_hub/kustomization.yaml
  manifests/overlays/prod/secrets/clusters/api.datahub-ocp4.prod.psi.redhat.com.enc.yaml
Labels: approved, size/S, lgtm

#739 Remove old prod superset app
  manifests/overlays/prod/applications/data_hub/dh-prod-superset.yaml
  manifests/overlays/prod/applications/data_hub/kustomization.yaml
  manifests/overlays/prod/secrets/clusters/datahub.psi.redhat.com.enc.yaml
Labels: approved, size/S, lgtm

#740 Add redis patch to remove upstream SCC specifications
  manifests/overlays/prod/deployments/argocd-redis_patch.yaml
  manifests/overlays/prod/kustomization.yaml
Labels: size/XS, approved, lgtm

#741 Migrate stage superset to new stage cluster
  manifests/overlays/prod/applications/data_hub/dh-stage-superset.yaml
  manifests/overlays/prod/secrets/clusters/api.idh-stage.dev.datahub.redhat.com.enc.yaml
Labels: approved, size/M, lgtm

#742 Add idh-stage cluster config to secret generator
  manifests/overlays/prod/secrets/clusters/secret-generator.yaml
Labels: size/XS, lgtm

#743 Add inclusions for idh-stage cluster
  manifests/overlays/prod/configs/argo_cm/resource.inclusions
Labels: approved, size/S, lgtm
