Repository AICoE/aicoe-cd, pull requests merged in 2021-03, with the labels that each got.

#256 Replace .aicoe.yaml with .prow.yaml
  .aicoe-ci.yaml
  .prow.yaml
  test-kustomize-build
Labels: approved, lgtm, size/M

#258 Add SLO-reporter prod run from stage
  manifests/overlays/prod/applications/thoth-station/prod/kustomization.yaml
  manifests/overlays/prod/applications/thoth-station/prod/prod-slo-reporter.yaml
Labels: approved, size/S

#259 Add api.rhods-idh.dev.datahub.redhat.com server configuration
  docs/admin/add_new_cluster_spec.md
  manifests/overlays/prod/secrets/clusters/api.rhods-idh.dev.datahub.redhat.com.enc.yaml
  manifests/overlays/prod/secrets/clusters/secret-generator.yaml
Labels: approved, lgtm, size/M

#260 Fix stage cluster spec
  docs/admin/add_new_cluster_spec.md
  manifests/overlays/prod/secrets/clusters/secret-generator.yaml
Labels: approved, size/XS

#262 Add ODH operator required namespaces
  manifests/overlays/prod/secrets/clusters/api.rhods-idh.dev.datahub.redhat.com.enc.yaml
Labels: approved, lgtm, size/XS

#264 Add new repository
  manifests/overlays/prod/configs/argo_cm/repositories
Labels: approved, lgtm, size/XS

#266 Add Stage ODH Deployment
  manifests/overlays/prod/applications/data_hub/dh-stage-rhods-catalog.yaml
  manifests/overlays/prod/applications/data_hub/dh-stage-rhods-objects.yaml
  manifests/overlays/prod/applications/data_hub/kustomization.yaml
Labels: approved, lgtm, size/M

#267 Change null to '{}' for stage ODH apps
  manifests/overlays/prod/applications/data_hub/dh-stage-rhods-catalog.yaml
  manifests/overlays/prod/applications/data_hub/dh-stage-rhods-objects.yaml
Labels: approved, lgtm, size/XS

#261 Presto stage
  manifests/overlays/prod/applications/data_hub/dh-stage-trino.yaml
  manifests/overlays/prod/configs/argo_cm/resource.inclusions
  manifests/overlays/prod/secrets/clusters/api.rhods-idh.dev.datahub.redhat.com.enc.yaml
Labels: approved, lgtm, size/M

#269 Remove dh-stage-trino from api.rhods-idh.dev.datahub.redhat.com cluster
  manifests/overlays/prod/secrets/clusters/api.rhods-idh.dev.datahub.redhat.com.enc.yaml
Labels: approved, lgtm, size/S

#263 support thoth-prescription job with the argocd
  manifests/overlays/prod/applications/thoth-station/ocp4-stage/kustomization.yaml
  manifests/overlays/prod/applications/thoth-station/ocp4-stage/stage-thoth-prescription-sync.yaml
  manifests/overlays/prod/applications/thoth-station/test/kustomization.yaml
  manifests/overlays/prod/applications/thoth-station/test/test-thoth-prescription-sync.yaml
Labels: approved, lgtm, size/M

#270 Add odh monitoring namespace
  manifests/overlays/prod/secrets/clusters/api.rhods-idh.dev.datahub.redhat.com.enc.yaml
Labels: approved, lgtm, size/XS
