Repository AICoE/aicoe-cd, pull requests merged in 2021-11, with the labels that each got.

#722 Remove logstash applications
  manifests/overlays/prod/applications/data_hub/dh-prod-logstash.yaml
  manifests/overlays/prod/applications/data_hub/dh-stage-logstash.yaml
  manifests/overlays/prod/applications/data_hub/kustomization.yaml
Labels: approved, size/M, lgtm

#724 Migrate trino
  manifests/overlays/prod/applications/data_hub/dh-prod-trino.ocp4.yaml
  manifests/overlays/prod/applications/data_hub/kustomization.yaml
  manifests/overlays/prod/secrets/clusters/api.datahub-ocp4.prod.psi.redhat.com.enc.yaml
Labels: approved, size/M, lgtm

#723 Add applications for stage deployment of RHODS
  manifests/overlays/prod/applications/data_hub/dh-stage-rhods-catalog.yaml
  manifests/overlays/prod/applications/data_hub/dh-stage-rhods-objects.yaml
  manifests/overlays/prod/applications/data_hub/kustomization.yaml
  manifests/overlays/prod/applications/data_hub/redhat-ods-applications-stage.yaml
  manifests/overlays/prod/applications/data_hub/redhat-ods-monitoring-stage.yaml
  manifests/overlays/prod/applications/data_hub/redhat-ods-operator-stage.yaml
  manifests/overlays/prod/secrets/clusters/api.rhods-idh.dev.datahub.redhat.com.enc.yaml
Labels: size/L, approved, lgtm

#725 Disable autosync for dh-prod-trino app
  manifests/overlays/prod/applications/data_hub/dh-prod-trino.yaml
Labels: size/XS, approved, lgtm

#726 Enable Autosync for Obslytics
  manifests/overlays/prod/applications/data_hub/dh-prod-obslytics.ocp4.yaml
  manifests/overlays/prod/applications/data_hub/dh-prod-obslytics.yaml
Labels: approved, size/S, lgtm

#727 Add application definitions for prod and stage dh-docs
  manifests/overlays/prod/applications/data_hub/dh-prod-docs.yaml
  manifests/overlays/prod/applications/data_hub/dh-stage-docs.yaml
  manifests/overlays/prod/applications/data_hub/kustomization.yaml
  manifests/overlays/prod/secrets/clusters/api.datahub-ocp4.prod.psi.redhat.com.enc.yaml
  manifests/overlays/prod/secrets/clusters/api.rhods-idh.dev.datahub.redhat.com.enc.yaml
Labels: approved, size/M, lgtm

#728 Deploy Blackbox Exporter on Datahub-ocp4 cluster
  manifests/overlays/prod/applications/data_hub/dh-prod-monitoring.yaml
  manifests/overlays/prod/applications/data_hub/kustomization.yaml
  manifests/overlays/prod/secrets/clusters/api.datahub-ocp4.prod.psi.redhat.com.enc.yaml
Labels: approved, size/S, lgtm

#729 Remove dh-prod-thanos-extractor app
  manifests/overlays/prod/applications/data_hub/dh-prod-thanos-extractor.yaml
  manifests/overlays/prod/applications/data_hub/kustomization.yaml
  manifests/overlays/prod/secrets/clusters/datahub.psi.redhat.com.enc.yaml
Labels: approved, size/S, lgtm

#731 Remove namespace dh-prod-customer-journeys
  manifests/overlays/prod/secrets/clusters/datahub.psi.redhat.com.enc.yaml
Labels: size/XS, approved

#730 Remove dh-prod-obslytics application
  manifests/overlays/prod/applications/data_hub/dh-prod-obslytics.yaml
  manifests/overlays/prod/applications/data_hub/kustomization.yaml
Labels: approved, size/S, lgtm

#732 Remove old Trino app
  manifests/overlays/prod/applications/data_hub/dh-prod-trino.yaml
  manifests/overlays/prod/applications/data_hub/kustomization.yaml
Labels: approved, size/S, lgtm

#734 Remove broken stage applications from kustomization
  manifests/overlays/prod/applications/data_hub/kustomization.yaml
Labels: size/XS, approved, lgtm

#735 Upgrade argocd to 2.1.3.
  manifests/base/kustomization.yaml
  manifests/crds/kustomization.yaml
Labels: size/XS, approved, lgtm

#736 Add helm plugin env var to repo server.
  manifests/overlays/prod/deployments/argocd-repo-server_patch.yaml
Labels: size/XS, approved, lgtm
