Repository AICoE/aicoe-cd, pull requests merged in 2021-01, with the labels that each got.

#206 move thoth test apps from ocp4.3 to ocp4.5
  manifests/overlays/prod/applications/thoth-station/test/core-test.yaml
  manifests/overlays/prod/applications/thoth-station/test/test-thoth-advise-reporter.yaml
  manifests/overlays/prod/applications/thoth-station/test/test-thoth-adviser.yaml
  manifests/overlays/prod/applications/thoth-station/test/test-thoth-amun.yaml
  manifests/overlays/prod/applications/thoth-station/test/test-thoth-chat-notification.yaml
  manifests/overlays/prod/applications/thoth-station/test/test-thoth-cve-update.yaml
  manifests/overlays/prod/applications/thoth-station/test/test-thoth-graph-backup.yaml
  manifests/overlays/prod/applications/thoth-station/test/test-thoth-graph-refresh.yaml
  manifests/overlays/prod/applications/thoth-station/test/test-thoth-graph-sync.yaml
  manifests/overlays/prod/applications/thoth-station/test/test-thoth-investigator.yaml
  manifests/overlays/prod/applications/thoth-station/test/test-thoth-kebechet.yaml
  manifests/overlays/prod/applications/thoth-station/test/test-thoth-management-api.yaml
  manifests/overlays/prod/applications/thoth-station/test/test-thoth-metrics-exporter.yaml
  manifests/overlays/prod/applications/thoth-station/test/test-thoth-mi-scheduler.yaml
  manifests/overlays/prod/applications/thoth-station/test/test-thoth-package-extract.yaml
  manifests/overlays/prod/applications/thoth-station/test/test-thoth-package-releases.yaml
  manifests/overlays/prod/applications/thoth-station/test/test-thoth-package-update.yaml
  manifests/overlays/prod/applications/thoth-station/test/test-thoth-qeb-hwt.yaml
  manifests/overlays/prod/applications/thoth-station/test/test-thoth-revsolver.yaml
  manifests/overlays/prod/applications/thoth-station/test/test-thoth-security-indicators.yaml
  manifests/overlays/prod/applications/thoth-station/test/test-thoth-slo-reporter.yaml
  manifests/overlays/prod/applications/thoth-station/test/test-thoth-solver.yaml
  manifests/overlays/prod/applications/thoth-station/test/test-thoth-user-api.yaml
Labels: approved, size/M

#207 feat: Add prod solgate
  manifests/overlays/prod/applications/aiops/kustomization.yaml
  manifests/overlays/prod/applications/aiops/solgate.yaml
  manifests/overlays/prod/configs/argo_cm/repositories
Labels: approved, size/S

#203 move thoth bots from ocp4.3 to ocp4.5
  manifests/overlays/prod/applications/thoth-station/bots/thoth-nepthys.yaml
  manifests/overlays/prod/applications/thoth-station/bots/thoth-sefkhet-abwy.yaml
Labels: approved, size/S

#208 Upgrade ArgoCD to 1.8.1
  manifests/base/kustomization.yaml
  manifests/crds/kustomization.yaml
  manifests/overlays/prod/deployments/argocd-dex-server_patch.yaml
  manifests/overlays/prod/deployments/argocd-redis_patch.yaml
  manifests/overlays/prod/deployments/argocd-server_patch.yaml
  manifests/overlays/prod/kustomization.yaml
  manifests/overlays/prod/statefulsets/argocd-application-controller_patch.yaml
Labels: approved, size/M

#210 Revert "Upgrade ArgoCD to 1.8.1"
  manifests/base/kustomization.yaml
  manifests/crds/kustomization.yaml
  manifests/overlays/prod/deployments/argocd-application-controller_patch.yaml
  manifests/overlays/prod/deployments/argocd-dex-server_patch.yaml
  manifests/overlays/prod/deployments/argocd-redis_patch.yaml
  manifests/overlays/prod/deployments/argocd-server_patch.yaml
  manifests/overlays/prod/kustomization.yaml
Labels: approved, size/M

#205 feat: Add IDH Argo/Argo Events
  manifests/overlays/prod/applications/data_hub/dh-prod-argo.yaml
  manifests/overlays/prod/applications/data_hub/dh-stage-argo.yaml
  manifests/overlays/prod/applications/data_hub/kustomization.yaml
Labels: approved, size/M

#212 Fix Argo Workflow Permissions
  .github/CODEOWNERS
  OWNERS
  manifests/overlays/prod/configs/argo_cm/resource.exclusions
Labels: approved, size/S

#204 Remove dh-prod-customer-journeys app
  manifests/overlays/prod/applications/data_hub/dh-prod-customer-journeys.yaml
  manifests/overlays/prod/applications/data_hub/kustomization.yaml
Labels: approved, size/S

#214 Add dh-stage-argo namespace to stage cluster spec
  manifests/overlays/prod/secrets/clusters/paas.stage.psi.redhat.com.enc.yaml
Labels: approved, size/XS

#215 Fix cluster target for dh-stage-argo app
  manifests/overlays/prod/applications/data_hub/dh-stage-argo.yaml
Labels: approved, size/XS

#213 Increase replica count for repo_server & exec timeout
  manifests/overlays/prod/deployments/argocd-repo-server_patch.yaml
  manifests/overlays/prod/kustomization.yaml
Labels: approved, size/S

#216 Fix repo server timout env var to string
  manifests/overlays/prod/deployments/argocd-repo-server_patch.yaml
Labels: approved, size/XS

#217 Upgrade ArgoCD to 1.8.1
  OWNERS
  manifests/base/kustomization.yaml
  manifests/crds/kustomization.yaml
  manifests/overlays/prod/deployments/argocd-dex-server_patch.yaml
  manifests/overlays/prod/deployments/argocd-redis_patch.yaml
  manifests/overlays/prod/deployments/argocd-server_patch.yaml
  manifests/overlays/prod/kustomization.yaml
  manifests/overlays/prod/statefulsets/argocd-application-controller_patch.yaml
Labels: approved, size/M

#218 Increase reposerver exec timeout
  manifests/overlays/prod/deployments/argocd-repo-server_patch.yaml
Labels: approved, size/XS

#220 Optimize repo server
  manifests/overlays/prod/deployments/argocd-repo-server_patch.yaml
Labels: approved, size/S

#221 Scale up app controller
  manifests/overlays/prod/statefulsets/argocd-application-controller_patch.yaml
Labels: approved, size/XS

#211 Add graph-update-schema
  manifests/overlays/prod/applications/thoth-station/stage/kustomization.yaml
  manifests/overlays/prod/applications/thoth-station/stage/stage-thoth-graph-schema-update.yaml
  manifests/overlays/prod/applications/thoth-station/test/kustomization.yaml
  manifests/overlays/prod/applications/thoth-station/test/test-thoth-graph-schema-update.yaml
Labels: approved, size/M

#222 Anomaly Detect: Use master branch in parent repo
  manifests/overlays/prod/applications/aiops/argo-anomaly.yaml
  manifests/overlays/prod/configs/argo_cm/repositories
Labels: approved, size/XS

#223 Turn off autosync for app of apps
  manifests/overlays/prod/applications/argocd/argocd-apps.yaml
Labels: approved, size/XS

#224 Disable auto-sync for Stage Applications
  manifests/overlays/prod/applications/data_hub/dh-stage-argo.yaml
  manifests/overlays/prod/applications/data_hub/dh-stage-jupyterhub.yaml
  manifests/overlays/prod/applications/data_hub/dh-stage-kafka.yaml
  manifests/overlays/prod/applications/data_hub/dh-stage-logstash.yaml
  manifests/overlays/prod/applications/data_hub/dh-stage-rsyslog.yaml
Labels: approved, size/S

#228 Add replica count to app controller as env var
  manifests/overlays/prod/statefulsets/argocd-application-controller_patch.yaml
Labels: approved, size/XS

#227 Add dh-prod-argo to ArgoCD managed applications
  manifests/overlays/prod/applications/data_hub/kustomization.yaml
Labels: approved, size/XS

#229 ignore the difference of image causing out-of-sync issue
  manifests/overlays/prod/applications/aiops/argo-anomaly.yaml
  manifests/overlays/prod/applications/thoth-station/ocp4-stage/core-middletier.yaml
  manifests/overlays/prod/applications/thoth-station/ocp4-stage/stage-thoth-amun-inspection.yaml
  manifests/overlays/prod/applications/thoth-station/stage/stage-thoth-amun-inspection.yaml
Labels: approved, size/S

#231 Remove autosync from ocp4-anomaly app
  manifests/overlays/prod/applications/aiops/argo-anomaly.yaml
Labels: approved, size/XS

#232 Add dh-prod-argo namespace
  manifests/overlays/prod/secrets/clusters/datahub.psi.redhat.com.enc.yaml
Labels: approved, size/XS

#234 ignore image difference for stage thoth-core-middletier
  manifests/overlays/prod/applications/thoth-station/stage/core-middletier.yaml
Labels: approved, size/XS

#235 update the source target path for aicoe-ci deployment
  manifests/overlays/prod/applications/thoth-station/bots/aicoe-ci.yaml
Labels: approved, size/XS

#236 decommission thoth-station application from ocp stage
  manifests/overlays/prod/applications/thoth-station/kustomization.yaml
Labels: approved, size/XS

#237 Update replica count
  manifests/overlays/prod/secrets/clusters/k-openshift.osh.massopen.cloud.enc.yaml
  manifests/overlays/prod/secrets/clusters/secret-generator.yaml
  manifests/overlays/prod/statefulsets/argocd-application-controller_patch.yaml
Labels: approved, size/M

#238 Allocate clusters to appropriate shards
  manifests/overlays/prod/secrets/clusters/api.ocp4.prod.psi.redhat.com.enc.yaml
  manifests/overlays/prod/secrets/clusters/apps.ocp.prod.psi.redhat.com.enc.yaml
  manifests/overlays/prod/secrets/clusters/datahub.psi.redhat.com.enc.yaml
  manifests/overlays/prod/secrets/clusters/paas.stage.psi.redhat.com.enc.yaml
Labels: approved, size/S

#239 Fix yaml string to conversion issue in yaml for shards
  manifests/overlays/prod/secrets/clusters/api.ocp4.prod.psi.redhat.com.enc.yaml
  manifests/overlays/prod/secrets/clusters/apps.ocp.prod.psi.redhat.com.enc.yaml
  manifests/overlays/prod/secrets/clusters/datahub.psi.redhat.com.enc.yaml
  manifests/overlays/prod/secrets/clusters/paas.stage.psi.redhat.com.enc.yaml
Labels: approved, size/S
