Repository AICoE/aicoe-cd, pull requests merged in 2021-06, with the labels that each got.

#283 Add dh-stage-trino in api.rhods-idh.dev.redhat.com cluster
  manifests/overlays/prod/configs/argo_cm/resource.inclusions
  manifests/overlays/prod/secrets/clusters/api.rhods-idh.dev.datahub.redhat.com.enc.yaml
Labels: approved, lgtm, size/XS

#284 Fix inclusion file for ocp 3.11 and argo objects
  manifests/overlays/prod/configs/argo_cm/resource.inclusions
Labels: approved, lgtm, size/XS

#280 Remove old PSI OCP4 cluster
  manifests/overlays/prod/configs/argo_cm/dex.config
  manifests/overlays/prod/configs/argo_cm/resource.inclusions
  manifests/overlays/prod/secrets/clusters/apps.ocp.prod.psi.redhat.com.enc.yaml
  manifests/overlays/prod/secrets/clusters/secret-generator.yaml
Labels: approved, lgtm, size/L

#285 Fix ArgoCD configuration for OCP 3.11 clusters
  manifests/overlays/prod/configs/argo_cm/resource.inclusions
Labels: approved, lgtm, size/XS

#286 Move stage kafka to new cluster
  manifests/overlays/prod/applications/data_hub/dh-stage-kafka.yaml
  manifests/overlays/prod/secrets/clusters/api.rhods-idh.dev.datahub.redhat.com.enc.yaml
  manifests/overlays/prod/secrets/clusters/paas.stage.psi.redhat.com.enc.yaml
Labels: approved, lgtm, size/M

#287 Copy stage inclusions to rhods-idh
  manifests/overlays/prod/configs/argo_cm/resource.inclusions
Labels: approved, lgtm, size/S

#288 remove the prescription sync job as it is deprecated
  manifests/overlays/prod/applications/thoth-station/ocp4-stage/kustomization.yaml
  manifests/overlays/prod/applications/thoth-station/ocp4-stage/stage-thoth-prescription-sync.yaml
  manifests/overlays/prod/applications/thoth-station/test/kustomization.yaml
  manifests/overlays/prod/applications/thoth-station/test/test-thoth-prescription-sync.yaml
Labels: approved, lgtm, size/M

#289 Introduce thoth graph-metrics-exporter component
  manifests/overlays/prod/applications/thoth-station/ocp4-stage/kustomization.yaml
  manifests/overlays/prod/applications/thoth-station/ocp4-stage/stage-thoth-graph-metrics-exporter.yaml
Labels: approved, lgtm, size/S

#290 migrated to graph namespace for staging environment (thoth-station/thoth-application issue #1166)
  manifests/overlays/prod/applications/data_hub/dh-prod-argo.yaml
  manifests/overlays/prod/applications/thoth-station/ocp4-stage/stage-thoth-graph-backup.yaml
Labels: approved, lgtm, size/XS

#292 Change git repository for dh-stage-trino
  manifests/overlays/prod/applications/data_hub/dh-stage-trino.yaml
Labels: approved, size/XS

#291 Deprecate Qeb-hwt component
  manifests/overlays/prod/applications/thoth-station/ocp4-stage/kustomization.yaml
  manifests/overlays/prod/applications/thoth-station/ocp4-stage/stage-thoth-qeb-hwt.yaml
  manifests/overlays/prod/applications/thoth-station/test/kustomization.yaml
  manifests/overlays/prod/applications/thoth-station/test/test-thoth-qeb-hwt.yaml
Labels: approved, lgtm, size/M

#293 Fix dh-stage-trino kustomize path
  manifests/overlays/prod/applications/data_hub/dh-stage-trino.yaml
Labels: do-not-merge/hold, size/XS

#294 Fix typos in application manifests
  manifests/overlays/prod/applications/data_hub/dh-stage-trino.yaml
  manifests/overlays/prod/applications/thoth-station/ocp4-stage/stage-thoth-graph-metrics-exporter.yaml
Labels: approved, lgtm, size/XS

#299 update the resource limit for the prowjobs
  .prow.yaml
Labels: approved, lgtm, size/XS

#297 Change deployment repo for dh-prod-trino
  manifests/overlays/prod/applications/data_hub/dh-prod-trino.yaml
Labels: approved, lgtm, size/XS

#296 change the deployment namespace for thoth task
  manifests/overlays/prod/applications/thoth-station/ocp4-stage/stage-thoth-purge-job.yaml
Labels: approved, lgtm, size/XS

#298 Adjust path to manifests and add graph-metrics-exporter to test
  manifests/overlays/prod/applications/thoth-station/ocp4-stage/stage-thoth-graph-metrics-exporter.yaml
  manifests/overlays/prod/applications/thoth-station/test/kustomization.yaml
  manifests/overlays/prod/applications/thoth-station/test/test-thoth-graph-metrics-exporter.yaml
Labels: approved, lgtm, size/S
