Repository AICoE/aicoe-cd, pull requests merged in 2021-09, with the labels that each got.

#307 Remove auto-sync option from dh-prod-data-catalog-usir namespace
  manifests/overlays/prod/applications/data_hub/dh-prod-data-catalog-usir.yaml
Labels: size/XS, approved

#306 Remove dh-prod-data-catalog-usir from ArgoCD
  manifests/overlays/prod/applications/data_hub/dh-prod-data-catalog-usir.yaml
  manifests/overlays/prod/applications/data_hub/kustomization.yaml
  manifests/overlays/prod/secrets/clusters/datahub.psi.redhat.com.enc.yaml
Labels: approved, size/M

#310 Add Cluster Spec for Data Hub OCP4 cluster
  manifests/overlays/prod/secrets/clusters/api.datahub-ocp4.prod.psi.redhat.com.enc.yaml
Labels: approved, size/M, lgtm

#311 Add datahub-ocp4 cluster spec to secret generator
  manifests/overlays/prod/secrets/clusters/secret-generator.yaml
Labels: size/XS, approved, lgtm

#312 Fix Data Hub OCP4 cluster spec
  manifests/overlays/prod/secrets/clusters/api.datahub-ocp4.prod.psi.redhat.com.enc.yaml
Labels: size/XS, approved, lgtm

#314 Add datahub perms
  manifests/overlays/prod/applications/data_hub/dh-prod-argo.ocp4.yaml
  manifests/overlays/prod/applications/data_hub/dh-prod-thanos-extractor.ocp4.yaml
  manifests/overlays/prod/applications/data_hub/kustomization.yaml
  manifests/overlays/prod/secrets/clusters/api.datahub-ocp4.prod.psi.redhat.com.enc.yaml
Labels: approved, size/M, lgtm

#315 Add new Data Hub OCP4 cluster to the inclusions list
  manifests/overlays/prod/configs/argo_cm/resource.inclusions
Labels: size/S, lgtm

#316 Added lucferbux as owner
  OWNERS
Labels: size/XS, approved, lgtm

#317 Add RHODS namespaces
  manifests/overlays/prod/applications/data_hub/kustomization.yaml
  manifests/overlays/prod/applications/data_hub/redhat-ods-applications.yaml
  manifests/overlays/prod/applications/data_hub/redhat-ods-monitoring.yaml
  manifests/overlays/prod/applications/data_hub/redhat-ods-operator.yaml
  manifests/overlays/prod/secrets/clusters/api.datahub-ocp4.prod.psi.redhat.com.enc.yaml
Labels: approved, size/M, lgtm

#313 Add dh-prod-thanos-extractor and dh-prod-argo applications for DH-OCP4
  manifests/overlays/prod/applications/data_hub/dh-prod-argo.ocp4.yaml
  manifests/overlays/prod/applications/data_hub/dh-prod-thanos-extractor.ocp4.yaml
Labels: approved, size/M, lgtm

#318 Point stage rhods applications at github repository
  manifests/overlays/prod/applications/data_hub/dh-stage-rhods-catalog.yaml
  manifests/overlays/prod/applications/data_hub/dh-stage-rhods-objects.yaml
Labels: size/XS, approved
