Repository AICoE/aicoe-cd, pull requests merged in 2021-05, with the labels that each got.

#277 feat: Remove Argo-Events
  manifests/overlays/prod/applications/data_hub/dh-prod-argo.yaml
  manifests/overlays/prod/applications/data_hub/dh-stage-argo.yaml
Labels: approved, lgtm, size/M

#279 enable the purge job to be deployed
  manifests/overlays/prod/applications/thoth-station/ocp4-stage/kustomization.yaml
  manifests/overlays/prod/applications/thoth-station/ocp4-stage/stage-thoth-purge-job.yaml
  manifests/overlays/prod/applications/thoth-station/test/kustomization.yaml
  manifests/overlays/prod/applications/thoth-station/test/test-thoth-purge-job.yaml
Labels: approved, lgtm, size/M

#281 Add argo-workflows application definition
  manifests/overlays/prod/applications/data_hub/dh-prod-argo.yaml
Labels: approved, lgtm, size/S

#282 Fix YAML syntax error in dh-prod-argo
  manifests/overlays/prod/applications/data_hub/dh-prod-argo.yaml
Labels: approved, lgtm, size/XS
