Repository AICoE/aicoe-cd, pull requests merged in 2021-02, with the labels that each got.

#240 Add dh-prod-thanos-extractor application
  manifests/overlays/prod/applications/data_hub/dh-prod-thanos-extractor.yaml
  manifests/overlays/prod/applications/data_hub/kustomization.yaml
  manifests/overlays/prod/secrets/clusters/datahub.psi.redhat.com.enc.yaml
Labels: approved, size/M

#241 ignore image difference for stage thoth cronjob
  manifests/overlays/prod/applications/thoth-station/ocp4-stage/stage-thoth-graph-refresh.yaml
  manifests/overlays/prod/applications/thoth-station/ocp4-stage/stage-thoth-package-releases.yaml
  manifests/overlays/prod/applications/thoth-station/ocp4-stage/stage-thoth-package-update.yaml
Labels: approved, size/S

#242 Fixed application typo to fix build for apps
  manifests/overlays/prod/applications/data_hub/kustomization.yaml
Labels: approved, size/XS

#243 disable autosync for amun for testing purposes
  manifests/overlays/prod/applications/thoth-station/test/test-thoth-amun.yaml
Labels: approved, lgtm, size/XS

#244 Include thoth integration tests app setup manifests
  manifests/overlays/prod/applications/thoth-station/ocp4-stage/kustomization.yaml
  manifests/overlays/prod/applications/thoth-station/ocp4-stage/stage-thoth-integration-tests.yaml
  manifests/overlays/prod/applications/thoth-station/test/kustomization.yaml
  manifests/overlays/prod/applications/thoth-station/test/test-thoth-integration-tests.yaml
Labels: approved, size/M

#245 Remove references to master in docs and Data Hub applications
  RUNBOOK.md
  docs/admin/add_namespace_to_cluster.md
  docs/argocd_project_permissions.md
  docs/create_argocd_application_manifest.md
  docs/get_argocd_to_manage_your_app.md
  docs/inclusions_explained.md
  docs/manage_your_app_secrets.md
  manifests/overlays/prod/applications/data_hub/dh-prod-logstash.yaml
  manifests/overlays/prod/applications/data_hub/dh-prod-rsyslog.yaml
  manifests/overlays/prod/applications/data_hub/dh-psi-monitoring.yaml
  manifests/overlays/prod/applications/data_hub/dh-stage-logstash.yaml
  manifests/overlays/prod/applications/data_hub/dh-stage-rsyslog.yaml
Labels: approved, size/M

#247 Remove argo-events from dh-prod-thanos-extractor
  manifests/overlays/prod/applications/data_hub/dh-prod-thanos-extractor.yaml
Labels: approved, size/S

#246 re-enable amun autosync
  manifests/overlays/prod/applications/thoth-station/test/test-thoth-amun.yaml
Labels: approved, lgtm, size/XS

#248 Ignore image differences in data hub stage analytics factory
  manifests/overlays/prod/applications/data_hub/dh-stage-analytics-factory.yaml
Labels: approved, size/S

#249 Ignore image diff in all Data Hub data catalog apps
  manifests/overlays/prod/applications/data_hub/dh-prod-analytics-factory.yaml
  manifests/overlays/prod/applications/data_hub/dh-prod-data-catalog-ccx.yaml
  manifests/overlays/prod/applications/data_hub/dh-prod-data-catalog-usir.yaml
  manifests/overlays/prod/applications/data_hub/dh-stage-analytics-factory.yaml
Labels: approved, size/M

#250 Enable auto-sync for all Data Hub applications
  manifests/overlays/prod/applications/data_hub/dh-prod-analytics-factory.yaml
  manifests/overlays/prod/applications/data_hub/dh-prod-argo.yaml
  manifests/overlays/prod/applications/data_hub/dh-prod-data-catalog-ccx.yaml
  manifests/overlays/prod/applications/data_hub/dh-prod-data-catalog-usir.yaml
  manifests/overlays/prod/applications/data_hub/dh-prod-jupyterhub.yaml
  manifests/overlays/prod/applications/data_hub/dh-prod-kafka.yaml
  manifests/overlays/prod/applications/data_hub/dh-prod-logstash.yaml
  manifests/overlays/prod/applications/data_hub/dh-prod-rsyslog.yaml
  manifests/overlays/prod/applications/data_hub/dh-prod-superset.yaml
  manifests/overlays/prod/applications/data_hub/dh-prod-thanos-extractor.yaml
  manifests/overlays/prod/applications/data_hub/dh-psi-monitoring.yaml
  manifests/overlays/prod/applications/data_hub/dh-stage-analytics-factory.yaml
  manifests/overlays/prod/applications/data_hub/dh-stage-argo.yaml
  manifests/overlays/prod/applications/data_hub/dh-stage-jupyterhub.yaml
  manifests/overlays/prod/applications/data_hub/dh-stage-kafka.yaml
  manifests/overlays/prod/applications/data_hub/dh-stage-logstash.yaml
  manifests/overlays/prod/applications/data_hub/dh-stage-rsyslog.yaml
  manifests/overlays/prod/applications/data_hub/dh-stage-superset.yaml
Labels: approved, size/M

#252 Move Argocd applications to dedicated project
  manifests/overlays/prod/applications/argocd-management/aicoe-argocd.yaml
  manifests/overlays/prod/applications/argocd-management/argocd-apps.yaml
  manifests/overlays/prod/applications/argocd-management/kustomization.yaml
  manifests/overlays/prod/configs/argo_rbac_cm/policy.csv
  manifests/overlays/prod/kustomization.yaml
  manifests/overlays/prod/projects/projects.yaml
Labels: approved, do-not-merge/hold, size/S

#253 clear the unused thoth-station stage app manifests
  manifests/overlays/prod/applications/thoth-station/stage/core-backend.yaml
  manifests/overlays/prod/applications/thoth-station/stage/core-frontend.yaml
  manifests/overlays/prod/applications/thoth-station/stage/core-graph.yaml
  manifests/overlays/prod/applications/thoth-station/stage/core-infra.yaml
  manifests/overlays/prod/applications/thoth-station/stage/core-middletier.yaml
  manifests/overlays/prod/applications/thoth-station/stage/kustomization.yaml
  manifests/overlays/prod/applications/thoth-station/stage/stage-thoth-advise-reporter.yaml
  manifests/overlays/prod/applications/thoth-station/stage/stage-thoth-adviser.yaml
  manifests/overlays/prod/applications/thoth-station/stage/stage-thoth-amun-api.yaml
  manifests/overlays/prod/applications/thoth-station/stage/stage-thoth-amun-inspection.yaml
  manifests/overlays/prod/applications/thoth-station/stage/stage-thoth-chat-notification.yaml
  manifests/overlays/prod/applications/thoth-station/stage/stage-thoth-cve-update.yaml
  manifests/overlays/prod/applications/thoth-station/stage/stage-thoth-graph-backup.yaml
  manifests/overlays/prod/applications/thoth-station/stage/stage-thoth-graph-refresh.yaml
  manifests/overlays/prod/applications/thoth-station/stage/stage-thoth-graph-schema-update.yaml
  manifests/overlays/prod/applications/thoth-station/stage/stage-thoth-graph-sync-backend.yaml
  manifests/overlays/prod/applications/thoth-station/stage/stage-thoth-graph-sync-middletier.yaml
  manifests/overlays/prod/applications/thoth-station/stage/stage-thoth-investigator.yaml
  manifests/overlays/prod/applications/thoth-station/stage/stage-thoth-kebechet.yaml
  manifests/overlays/prod/applications/thoth-station/stage/stage-thoth-management-api.yaml
  manifests/overlays/prod/applications/thoth-station/stage/stage-thoth-metrics-exporter.yaml
  manifests/overlays/prod/applications/thoth-station/stage/stage-thoth-mi.yaml
  manifests/overlays/prod/applications/thoth-station/stage/stage-thoth-package-extract.yaml
  manifests/overlays/prod/applications/thoth-station/stage/stage-thoth-package-releases.yaml
  manifests/overlays/prod/applications/thoth-station/stage/stage-thoth-package-update.yaml
  manifests/overlays/prod/applications/thoth-station/stage/stage-thoth-qeb-hwt.yaml
  manifests/overlays/prod/applications/thoth-station/stage/stage-thoth-revsolver.yaml
  manifests/overlays/prod/applications/thoth-station/stage/stage-thoth-security-indicators.yaml
  manifests/overlays/prod/applications/thoth-station/stage/stage-thoth-slo-reporter.yaml
  manifests/overlays/prod/applications/thoth-station/stage/stage-thoth-solver.yaml
  manifests/overlays/prod/applications/thoth-station/stage/stage-thoth-user-api.yaml
Labels: approved, lgtm, size/XL

#254 Clean up OWNERS file
  OWNERS
Labels: approved, lgtm, size/S

#255 Add Kustomize Build Test Script
  OWNERS
  test-kustomize-build
Labels: approved, size/M
