Repository AICoE/aicoe-cd, pull requests merged in 2022-08, with the labels that each got.

#782 Remove the dh-prod-data-catalog-ccx application
  manifests/overlays/prod/applications/data_hub/dh-prod-data-catalog-ccx.yaml
  manifests/overlays/prod/applications/data_hub/kustomization.yaml
  manifests/overlays/prod/secrets/clusters/datahub.psi.redhat.com.enc.yaml
Labels: approved, size/M, lgtm

#783 Remove the prod kafka application
  manifests/overlays/prod/applications/data_hub/dh-prod-kafka.yaml
  manifests/overlays/prod/applications/data_hub/kustomization.yaml
  manifests/overlays/prod/secrets/clusters/datahub.psi.redhat.com.enc.yaml
Labels: approved, size/S, lgtm

#785 Move our official stage superset instance to the prod cluster
  manifests/overlays/prod/applications/data_hub/dh-stage-superset.yaml
  manifests/overlays/prod/secrets/clusters/api.datahub-ocp4.prod.psi.redhat.com.enc.yaml
  manifests/overlays/prod/secrets/clusters/api.idh-stage.dev.datahub.redhat.com.enc.yaml
Labels: approved, size/S, lgtm

#786 Deprecate the deployment of pulp-metrics-exporter
  manifests/overlays/prod/applications/thoth-station/prod/kustomization.yaml
  manifests/overlays/prod/applications/thoth-station/prod/prod-thoth-pulp-metrics-exporter.yaml
Labels: approved, size/S
