Repository AICoE/aicoe-cd, pull requests merged in 2022-03, with the labels that each got.

#768 Update secrets file name for prod kafka
  manifests/overlays/prod/applications/data_hub/dh-prod-kafka.yaml
Labels: size/XS, approved, lgtm

#769 Add dh-prod-kfp-tekton namespace back
  manifests/overlays/prod/applications/data_hub/kustomization.yaml
  manifests/overlays/prod/configs/argo_cm/resource.inclusions
Labels: size/XS, approved

#770 Revert "Add dh-prod-kfp-tekton namespace back (#769)"
  manifests/overlays/prod/applications/data_hub/kustomization.yaml
  manifests/overlays/prod/configs/argo_cm/resource.inclusions
Labels: size/XS, lgtm

#771 Add definitely dh-prod-kfp-tekton
  manifests/overlays/prod/applications/data_hub/kustomization.yaml
  manifests/overlays/prod/configs/argo_cm/resource.inclusions
Labels: size/XS, approved

#773 updating pre-commit protocol to https
  .pre-commit-config.yaml
Labels: size/XS, approved, lgtm
