Repository AICoE/aicoe-cd, pull requests merged in 2022-02, with the labels that each got.

#748 Add Grafana to OCP4 Data Hub
  manifests/overlays/prod/applications/data_hub/dh-prod-monitoring-grafana.yaml
  manifests/overlays/prod/applications/data_hub/kustomization.yaml
Labels: approved, size/S, lgtm

#749 Allow ArgoCD to manage Grafana objects in Data Hub OCP4 cluster
  manifests/overlays/prod/configs/argo_cm/resource.inclusions
Labels: size/XS, approved, lgtm

#750 Delete old Grafana instance
  manifests/overlays/prod/applications/data_hub/dh-psi-monitoring.yaml
Labels: approved, size/S

#753 Fix dh-prod-camel-k kustomize path
  manifests/overlays/prod/applications/data_hub/dh-prod-camel-k.ocp4.yaml
Labels: size/XS, approved, lgtm

#754 Let datahub-ocp4.psi cluster manage dh-prod-camel-k
  manifests/overlays/prod/secrets/clusters/api.datahub-ocp4.prod.psi.redhat.com.enc.yaml
Labels: size/XS, approved, lgtm

#755 Added camel-k to resource.icnlusions
  manifests/overlays/prod/configs/argo_cm/resource.inclusions
Labels: approved, size/S, lgtm

#751 Set up argocd app for document sync
  manifests/overlays/prod/applications/thoth-station/ocp4-stage/kustomization.yaml
  manifests/overlays/prod/applications/thoth-station/ocp4-stage/stage-thoth-document-sync.yaml
  manifests/overlays/prod/applications/thoth-station/test/kustomization.yaml
  manifests/overlays/prod/applications/thoth-station/test/test-thoth-document-sync.yaml
Labels: approved, size/M, lgtm

#756 Migrate stage kafka to new stage cluster
  manifests/overlays/prod/applications/data_hub/dh-prod-kafka.yaml
  manifests/overlays/prod/applications/data_hub/dh-stage-kafka.yaml
  manifests/overlays/prod/secrets/clusters/api.idh-stage.dev.datahub.redhat.com.enc.yaml
Labels: approved, size/S, lgtm

#757 Disable artifact validation
  manifests/overlays/prod/applications/data_hub/dh-prod-kafka.yaml
  manifests/overlays/prod/applications/data_hub/dh-stage-kafka.yaml
Labels: approved, size/S, lgtm

#758 Disable automated sync for Prod Kafka
  manifests/overlays/prod/applications/data_hub/dh-prod-kafka.yaml
Labels: size/XS, lgtm

#760 Added workflow_dispatch to actions script
  .github/workflows/ci.yaml
Labels: size/XS, approved

#761 Add argo-workflows App for OCP4 cluster
  manifests/overlays/prod/applications/data_hub/dh-prod-argo.ocp4.yaml
Labels: approved, size/S

#762 Add application definition for s3 webserver
  manifests/overlays/prod/applications/data_hub/dh-prod-s3-webserver.yaml
  manifests/overlays/prod/applications/data_hub/kustomization.yaml
  manifests/overlays/prod/secrets/clusters/api.datahub-ocp4.prod.psi.redhat.com.enc.yaml
Labels: approved, size/S, lgtm

#763 Remove application definition for dh-prod-rsyslog
  manifests/overlays/prod/applications/data_hub/dh-prod-rsyslog.yaml
  manifests/overlays/prod/applications/data_hub/kustomization.yaml
  manifests/overlays/prod/secrets/clusters/api.ocp4.prod.psi.redhat.com.enc.yaml
Labels: size/S, lgtm

#764 Add dh-prod-kfp-tekton to ArgoCD
  manifests/overlays/prod/applications/data_hub/dh-prod-kfp-tekton.yaml
  manifests/overlays/prod/secrets/clusters/api.datahub-ocp4.prod.psi.redhat.com.enc.yaml
Labels: approved, size/S, lgtm

#765 Add Resource inclusion for kfp tekton CRDs
  manifests/overlays/prod/applications/data_hub/kustomization.yaml
  manifests/overlays/prod/configs/argo_cm/resource.inclusions
Labels: size/XS, approved, lgtm

#766 Update cluster for stage data hub apps
  manifests/overlays/prod/applications/data_hub/dh-stage-docs.yaml
  manifests/overlays/prod/applications/data_hub/dh-stage-rsyslog.yaml
  manifests/overlays/prod/applications/data_hub/dh-stage-telemetry-grafana.yaml
  manifests/overlays/prod/applications/data_hub/dh-stage-trino.yaml
  manifests/overlays/prod/applications/data_hub/redhat-ods-applications-stage.yaml
  manifests/overlays/prod/applications/data_hub/redhat-ods-monitoring-stage.yaml
  manifests/overlays/prod/applications/data_hub/redhat-ods-operator-stage.yaml
  manifests/overlays/prod/secrets/clusters/api.idh-stage.dev.datahub.redhat.com.enc.yaml
Labels: approved, size/M, lgtm

#767 Revert inclusion of Kubeflow Pipelines CRDs and dh-prod-kfp-tekton
  manifests/overlays/prod/applications/data_hub/kustomization.yaml
  manifests/overlays/prod/configs/argo_cm/resource.inclusions
Labels: size/XS, approved
